How do you make a game UI?

Image result for gaming website ui
How to make your game UI designs shine?
Make players understand your game naturally. ...
Guide players using the right method at the right time. ...
Allow players to skip things. ...
Make your rewards and in-app purchases stand out. ...
Never clutter game UI. ...
Create a clear visual hierarchy. ...
Make accessible navigation, like sidebar.
